# compute_environment: LOCAL_MACHINE
# debug: false
# deepspeed_config:
#   deepspeed_config_file: /mnt/cache/xuzhiguo/workspace/LLaMA-Factory/src/mytest/ds_config.json
# #  zero3_init_flag: true
# distributed_type: DEEPSPEED
# downcast_bf16: 'no'
# # dynamo_config:
# #   dynamo_backend: INDUCTOR
# machine_rank: 0
# main_training_function: main
# num_machines: 1
# num_processes: 1
# rdzv_backend: static
# same_network: true
# tpu_env: []
# tpu_use_cluster: false
# tpu_use_sudo: false
# use_cpu: false

compute_environment: LOCAL_MACHINE
deepspeed_config:
 deepspeed_config_file: /mnt/cache/xuzhiguo/workspace/LLaMA-Factory/src/mytest/ds3_config.json
 zero3_init_flag: true
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: 29500 # null
main_training_function: main
num_machines: 1
num_processes: 1
use_cpu: true